### ISSUE TITLE
generic "Internal Server Error" message

### ISSUE THREAD

**Issue by notslang** [derailed/mongo3#18]
http://localhost:6663/ opens and displays generic "Internal Server Error" message. Also, there is a issue with my landscape file, but even without it the result is the same. The output of mongo3 is below, but I cannot find any obvious indication to what is wrong.

```
sean@sean-HP-Pavilion-dv7-Notebook-PC:~$ mongo3
----------------------------------------------------------------------------------------------------
Initializing mongo3 -- Version 0.1.3
----------------------------------------------------------------------------------------------------


>>> Waiting for Franky to warm up...


:public is no longer used to avoid overloading Module#public, use :public_folder instead
    from /usr/lib/ruby/gems/1.8/gems/mongo3-0.1.3/bin/../lib/app.rb:10
[2011-11-22 18:19:43] INFO  WEBrick 1.3.1
[2011-11-22 18:19:43] INFO  ruby 1.8.7 (2011-06-30) [x86_64-linux]


>>> Opening console...


== Sinatra/1.3.1 has taken the stage on 6663 for production with backup from WEBrick
[2011-11-22 18:19:48] INFO  WEBrick::HTTPServer#start: pid=17064 port=6663
The :timeout option has been deprecated and will be removed in the 2.0 release. Use :pool_timeout instead.
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
RuntimeError - Unable to grok yaml landscape file. syntax error on line 1, col 6: ` host: localhost':
    /usr/lib/ruby/gems/1.8/gems/mongo3-0.1.3/lib/mongo3/connection.rb:492:in `config'
    /usr/lib/ruby/gems/1.8/gems/mongo3-0.1.3/lib/mongo3/connection.rb:219:in `build_tree'
    /usr/lib/ruby/gems/1.8/gems/mongo3-0.1.3/lib/controllers/explore.rb:22:in `GET /'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1211:in `call'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1211:in `compile!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in `[]'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in `route!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:788:in `route_eval'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in `route!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:821:in `process_route'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:819:in `catch'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:819:in `process_route'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:771:in `route!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:770:in `each'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:770:in `route!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:886:in `dispatch!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:706:in `call!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in `invoke'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in `catch'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in `invoke'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:706:in `call!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:692:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.5/lib/rack/session/abstract/id.rb:195:in `context'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.5/lib/rack/session/abstract/id.rb:190:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/xss_header.rb:22:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/path_traversal.rb:16:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/json_csrf.rb:17:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/base.rb:47:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/xss_header.rb:22:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.5/lib/rack/nulllogger.rb:9:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.5/lib/rack/head.rb:9:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.5/lib/rack/methodoverride.rb:24:in `call'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1334:in `call'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1403:in `synchronize'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1334:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.5/lib/rack/handler/webrick.rb:59:in `service'
    /usr/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
    /usr/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
    /usr/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
    /usr/lib/ruby/1.8/webrick/server.rb:162:in `start'
    /usr/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
    /usr/lib/ruby/1.8/webrick/server.rb:95:in `start'
    /usr/lib/ruby/1.8/webrick/server.rb:92:in `each'
    /usr/lib/ruby/1.8/webrick/server.rb:92:in `start'
    /usr/lib/ruby/1.8/webrick/server.rb:23:in `start'
    /usr/lib/ruby/1.8/webrick/server.rb:82:in `start'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.5/lib/rack/handler/webrick.rb:13:in `run'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1295:in `run!'
    /usr/lib/ruby/gems/1.8/gems/mongo3-0.1.3/bin/mongo3:45:in `run!'
    /usr/lib/ruby/gems/1.8/gems/main-4.8.0/lib/main/program/class_methods.rb:155:in `run'
    /usr/lib/ruby/gems/1.8/gems/main-4.8.0/lib/main/program/class_methods.rb:144:in `catch'
    /usr/lib/ruby/gems/1.8/gems/main-4.8.0/lib/main/program/class_methods.rb:144:in `run'
    /usr/lib/ruby/gems/1.8/gems/main-4.8.0/lib/main/factories.rb:18:in `run'
    /usr/lib/ruby/gems/1.8/gems/main-4.8.0/lib/main/factories.rb:25:in `Main'
    /usr/lib/ruby/gems/1.8/gems/mongo3-0.1.3/bin/mongo3:7
    /usr/local/bin/mongo3:19:in `load'
    /usr/local/bin/mongo3:19
localhost - - [22/Nov/2011:18:19:48 CST] "GET / HTTP/1.1" 500 30
- -> /
```

**Comment by kokizzu** [comment]
ah ic, i use wrong ruby and sinatra version

**Comment by Robsteranium** [comment]
This seems to do the trick: https://github.com/Robsteranium/mongo3/commit/c34ead35b6d2d860de0d6fe552ad6bae1e113276
