### ISSUE TITLE
Can not start mongo3

### ISSUE THREAD

**Issue by blocka** [derailed/mongo3#27]
Running Ubuntu 12.10 server

When I start, I get this:

```
/var/lib/gems/1.9.1/gems/mongo3-0.1.5/bin/mongo3:18: warning: class variable access from toplevel
/var/lib/gems/1.9.1/gems/mongo3-0.1.5/bin/mongo3:24: warning: class variable access from toplevel
----------------------------------------------------------------------------------------------------
Initializing mongo3 -- Version 0.1.5
----------------------------------------------------------------------------------------------------


>>> Waiting for Franky to warm up...


F, [2013-04-16T06:24:02.150194 #782] FATAL -- : undefined method `helpers' for CollectionHelper:Module (NoMethodError)
/var/lib/gems/1.9.1/gems/mongo3-0.1.5/lib/helpers/collection_helper.rb:15:in `<module:CollectionHelper>'
/var/lib/gems/1.9.1/gems/mongo3-0.1.5/lib/helpers/collection_helper.rb:14:in `<top (required)>'
/var/lib/gems/1.9.1/gems/mongo3-0.1.5/lib/mongo3.rb:49:in `load'
/var/lib/gems/1.9.1/gems/mongo3-0.1.5/lib/mongo3.rb:49:in `block in load_all_libs_relative_to'
/var/lib/gems/1.9.1/gems/mongo3-0.1.5/lib/mongo3.rb:49:in `each'
/var/lib/gems/1.9.1/gems/mongo3-0.1.5/lib/mongo3.rb:49:in `load_all_libs_relative_to'
/var/lib/gems/1.9.1/gems/mongo3-0.1.5/lib/app.rb:21:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1546:in `configure'
/var/lib/gems/1.9.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1915:in `block (2 levels) in delegate'
/var/lib/gems/1.9.1/gems/mongo3-0.1.5/lib/app.rb:20:in `<top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/var/lib/gems/1.9.1/gems/mongo3-0.1.5/bin/mongo3:44:in `run'
/var/lib/gems/1.9.1/gems/main-5.2.0/lib/main/program/class_methods.rb:155:in `block in run'
/var/lib/gems/1.9.1/gems/main-5.2.0/lib/main/program/class_methods.rb:144:in `catch'
/var/lib/gems/1.9.1/gems/main-5.2.0/lib/main/program/class_methods.rb:144:in `run'
/var/lib/gems/1.9.1/gems/main-5.2.0/lib/main/factories.rb:18:in `run'
/var/lib/gems/1.9.1/gems/main-5.2.0/lib/main/factories.rb:25:in `Main'
/var/lib/gems/1.9.1/gems/mongo3-0.1.5/bin/mongo3:7:in `<top (required)>'
/usr/local/bin/mongo3:23:in `load'
/usr/local/bin/mongo3:23:in `<main>'
```

**Comment by waltercacau** [comment]
I have the same issue on Mac OS X, using ruby 1.9.3p392 on rvm and mongo3 0.1.5

**Comment by gianpaj** [comment]
Same here:

```
$ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin12.2.1]
```

```
gem install mongo3
Fetching: bson-1.8.5.gem (100%)
Fetching: agnostic-will_paginate-3.0.0.gem (100%)
Fetching: memcache-client-1.8.5.gem (100%)
Fetching: mongo_ext-0.19.3.gem (100%)
Building native extensions.  This could take a while...
Fetching: mongo_rack-0.0.5.gem (100%)
Fetching: chronic-0.9.1.gem (100%)
Fetching: fattr-2.2.1.gem (100%)
Fetching: arrayfields-4.9.0.gem (100%)
Fetching: map-6.5.1.gem (100%)
Fetching: main-5.2.0.gem (100%)
Fetching: mongo3-0.1.5.gem (100%)
Successfully installed bson-1.8.5
Successfully installed agnostic-will_paginate-3.0.0
Successfully installed memcache-client-1.8.5
Successfully installed mongo_ext-0.19.3
Successfully installed mongo_rack-0.0.5
Successfully installed chronic-0.9.1
Successfully installed fattr-2.2.1
Successfully installed arrayfields-4.9.0
Successfully installed map-6.5.1
Successfully installed main-5.2.0
Successfully installed mongo3-0.1.5
11 gems installed
```

```
nitializing mongo3 -- Version 0.1.5
----------------------------------------------------------------------------------------------------


>>> Waiting for Franky to warm up...


F, [2013-05-14T17:54:12.267135 #35244] FATAL -- : undefined method `helpers' for CollectionHelper:Module (NoMethodError)
/Users/username/.rvm/gems/ruby-1.9.3-p194/gems/mongo3-0.1.5/lib/helpers/collection_helper.rb:15:in `<module:CollectionHelper>'
```

**Comment by zuk** [comment]
Same, after a fresh install on a clean system.

My rvm info is:

<pre>
ruby-1.9.3-p429:
  system:
    system:      "osx/10.7/x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.48(1)-release (x86_64-apple-darwin11)"
    zsh:         "/bin/zsh => zsh 4.3.11 (i386-apple-darwin11.0)"
  rvm:
    version:      "rvm 1.20.12 (stable) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "1 hour 44 minutes 51 seconds ago"
  ruby:
    interpreter:  "ruby"
    version:      "1.9.3p429"
    date:         "2013-05-15"
    platform:     "x86_64-darwin11.4.2"
    patchlevel:   "2013-05-15 revision 40747"
    full_version: "ruby 1.9.3p429 (2013-05-15 revision 40747) [x86_64-darwin11.4.2]"
  homes:
    gem:          "/Users/zuk/.rvm/gems/ruby-1.9.3-p429"
    ruby:         "/Users/zuk/.rvm/rubies/ruby-1.9.3-p429"
  binaries:
    ruby:         "/Users/zuk/.rvm/rubies/ruby-1.9.3-p429/bin/ruby"
    irb:          "/Users/zuk/.rvm/rubies/ruby-1.9.3-p429/bin/irb"
    gem:          "/Users/zuk/.rvm/rubies/ruby-1.9.3-p429/bin/gem"
    rake:         "/Users/zuk/.rvm/gems/ruby-1.9.3-p429@global/bin/rake"
  environment:
    PATH:         "/Users/zuk/.rvm/gems/ruby-1.9.3-p429/bin:/Users/zuk/.rvm/gems/ruby-1.9.3-p429@global/bin:/Users/zuk/.rvm/rubies/ruby-1.9.3-p429/bin:/Users/zuk/.rvm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/share/npm/bin"
    GEM_HOME:     "/Users/zuk/.rvm/gems/ruby-1.9.3-p429"
    GEM_PATH:     "/Users/zuk/.rvm/gems/ruby-1.9.3-p429:/Users/zuk/.rvm/gems/ruby-1.9.3-p429@global"
    MY_RUBY_HOME: "/Users/zuk/.rvm/rubies/ruby-1.9.3-p429"
    IRBRC:        "/Users/zuk/.rvm/rubies/ruby-1.9.3-p429/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
</pre>

**Comment by arturtr** [comment]
Same error

**Comment by Vanuan** [comment]
The workaround is to install a previous version of sinatra. 

```
$ sudo gem uninstall sinatra 
Select gem to uninstall:
 1. sinatra-1.4.2
 2. All versions
> 2

$ sudo gem install sinatra -v 1.3.3
```

**Comment by Zenexer** [comment]
Same problem here.  At the very least this is a Gemfile bug, as the dependency isn't specific enough.

**Comment by vcazan** [comment]
Still having the same issues.

**Comment by slikts** [comment]
This still happens.

**Comment by catalize** [comment]
I got this problem too, do you know how to solve it?
Mac OSX Maverick 10.9.2

**Comment by aleitner** [comment]
@Vanuan 's solution solved my issue. Sudo is unnecessary of course.

> gem uninstall sinatra 
> gem install sinatra -v 1.3.3
